CREATE TABLE IF NOT EXISTS leads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  extraction_type TEXT NOT NULL,
  status TEXT DEFAULT 'new',

  customer_first_name TEXT,
  customer_first_name_confidence REAL DEFAULT 0,
  customer_last_name TEXT,
  customer_last_name_confidence REAL DEFAULT 0,
  phone TEXT,
  phone_confidence REAL DEFAULT 0,
  email TEXT,
  email_confidence REAL DEFAULT 0,
  address TEXT,
  address_confidence REAL DEFAULT 0,

  voi_year TEXT,
  voi_year_confidence REAL DEFAULT 0,
  voi_make TEXT,
  voi_make_confidence REAL DEFAULT 0,
  voi_model TEXT,
  voi_model_confidence REAL DEFAULT 0,
  voi_trim TEXT,
  voi_trim_confidence REAL DEFAULT 0,
  voi_color TEXT,
  voi_color_confidence REAL DEFAULT 0,
  voi_stock_number TEXT,
  voi_stock_number_confidence REAL DEFAULT 0,
  voi_vin TEXT,
  voi_vin_confidence REAL DEFAULT 0,
  voi_new_or_used TEXT,
  voi_new_or_used_confidence REAL DEFAULT 0,

  trade_year TEXT,
  trade_year_confidence REAL DEFAULT 0,
  trade_make TEXT,
  trade_make_confidence REAL DEFAULT 0,
  trade_model TEXT,
  trade_model_confidence REAL DEFAULT 0,
  trade_trim TEXT,
  trade_trim_confidence REAL DEFAULT 0,
  trade_color TEXT,
  trade_color_confidence REAL DEFAULT 0,
  trade_mileage TEXT,
  trade_mileage_confidence REAL DEFAULT 0,
  trade_condition TEXT,
  trade_condition_confidence REAL DEFAULT 0,
  trade_payoff TEXT,
  trade_payoff_confidence REAL DEFAULT 0,
  trade_owned_or_leased TEXT,
  trade_owned_or_leased_confidence REAL DEFAULT 0,

  budget_monthly TEXT,
  budget_monthly_confidence REAL DEFAULT 0,
  budget_total TEXT,
  budget_total_confidence REAL DEFAULT 0,
  down_payment TEXT,
  down_payment_confidence REAL DEFAULT 0,
  financing_interest TEXT,
  financing_interest_confidence REAL DEFAULT 0,
  credit_concerns TEXT,
  credit_concerns_confidence REAL DEFAULT 0,
  co_buyer TEXT,
  co_buyer_confidence REAL DEFAULT 0,

  appointment_set INTEGER DEFAULT 0,
  appointment_set_confidence REAL DEFAULT 0,
  appointment_date TEXT,
  appointment_date_confidence REAL DEFAULT 0,
  appointment_time TEXT,
  appointment_time_confidence REAL DEFAULT 0,

  customer_intent TEXT,
  customer_intent_confidence REAL DEFAULT 0,
  visit_type TEXT,
  visit_type_confidence REAL DEFAULT 0,

  salesperson_name TEXT,
  salesperson_name_confidence REAL DEFAULT 0,
  lead_source TEXT,
  lead_source_confidence REAL DEFAULT 0,

  call_summary TEXT,
  additional_notes TEXT,
  objections TEXT,

  flag_urgent INTEGER DEFAULT 0,
  flag_needs_manager INTEGER DEFAULT 0,
  flag_duplicate_suspect INTEGER DEFAULT 0,
  flag_reason TEXT,

  raw_transcript TEXT,
  raw_image_path TEXT
);
